name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Adicionar serviço PostgreSQL aqui
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: zdb
          POSTGRES_USER: zuser
          POSTGRES_PASSWORD: zpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        env:
          DATABASE_URL: postgres://zuser:zpass@localhost:5432/zdb
          DATABASE_HOST: localhost
          POSTGRES_DB: zdb
          POSTGRES_USER: zuser
          POSTGRES_PASSWORD: zpass
        run: |
          python manage.py test
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          generate_release_notes: true
#      - name: Deploy to PythonAnywhere
#        run: |
#          ssh ${{ secrets.PA_USER }}@${{ secrets.PA_HOST }} "cd ~/z-project && git pull && docker-compose up -d"
